### ISSUE TITLE
"Give me a random integer between x and y" can't detect if x and y are both integers

### ISSUE THREAD

**Issue by cherche** [cherche/fuchsia#12]

**Comment by Bergenfrundt** [comment]
is there no if.morethanonecharacter or something?

**Comment by cherche** [comment]
Well, it would be `if(x.length > 1`), but that's not very useful in checking if the number is an integer.

**Comment by cherche** [comment]
This was a mistake on my end. I was supposed to use `!isNaN(y)` instead of `y !== NaN`.
